### ISSUE TITLE
failed to read mobData packet buffer when trying to join server

### ISSUE THREAD

**Issue by tommy10622** [Corgam/CagedMobs#13] opened 2020-12-01 02:17 UTC
So basically the server starts and runs fine but as soon as someone tries to join they get this error (internal exception: ionetty.handler.codec.DecoderException:java.lang.illegalState.exception: failed to read mobData from packet buffer.

Im not 100% Sure if this is to do with something on my side but if i remove the mod from both server and client then it runs fine cheers

**Comment by Corgam** [comment] 2020-12-01 11:35
Thanks for information, which mods are you using? And did you already place a cage in the world or was it your first log in?

**Comment by tommy10622** [comment] 2020-12-02 01:38
im only using a small modpack filled with just quality of life mods if u need me to list them all just let me know, this error occurs on the first log in on a brand new world

**Comment by Corgam** [comment] 2020-12-02 09:22
If you can, please give me the list of the mods. One of them could be the problem

**Comment by DrUltraLux** [comment] 2020-12-02 09:30
Can confirm the same problem working on a modpack. Runs fine single player, can start a dedicated server, but when a player joins the server this error occurs. 
Our modpack is well over 200 mods, so narrowing it down is pretty painful. 

However if Tommy can post his much smaller list, I'll cross-reference it with this modpack list to help find where the clash is.

**Comment by MachinegunMarty** [comment] 2020-12-02 11:52
[Minecraft_Mods.txt](https://github.com/Corgam/CagedMobs/files/5629104/Minecraft_Mods.txt)
Might as well leave my issue closed, i will respond in this one.
When connecting to 1.16.4 server, 1.2.5 still gives the error Failed to read mobData from packet buffer.

Version 1.2.2 is the last one that works, and doesn't give this error.

Edit: added my mod list

**Comment by Corgam** [comment] 2020-12-02 18:13
I tried to find the cause, but no luck yet. I added a line of code that should print more info about the error if it happens in the next update.

**Comment by DrUltraLux** [comment] 2020-12-02 21:09
> I tried to find the cause, but no luck yet. I added a line of code that should print more info about the error if it happens in the next update.

That would help. My guess is that it is trying to parse a mob from another mod for the cages and running into a type error or some such. I'll see if I can work out the clash from random guessing today. Wish me luck. lol

**Comment by DrUltraLux** [comment] 2020-12-02 22:54
> [Minecraft_Mods.txt](https://github.com/Corgam/CagedMobs/files/5629104/Minecraft_Mods.txt)
> Might as well leave my issue closed, i will respond in this one.
> When connecting to 1.16.4 server, 1.2.5 still gives the error Failed to read mobData from packet buffer.
> 
> Version 1.2.2 is the last one that works, and doesn't give this error.
> 
> Edit: added my mod list

OK. I went through everything on that list that is also in our modpack, disabling and reenabling them one by one, rebuilding the world and restarting the server every time, and the error continues. 

So if that is a complete list of all mods, then that means this error is occuring with multiple mods.

**Comment by Corgam** [comment] 2020-12-03 10:14
> > I tried to find the cause, but no luck yet. I added a line of code that should print more info about the error if it happens in the next update.
> 
> That would help. My guess is that it is trying to parse a mob from another mod for the cages and running into a type error or some such. I'll see if I can work out the clash from random guessing today. Wish me luck. lol

Other thing I'm thinking about is something that I changed after 1.2.2 version of the mod, because as MachinegunMarty said it works with that version. But to be honest I have no idea what's wrong... arrow upgrade was introduced but it shouldn't break everything. Maybe as you said it's a problem with other mod support

**Comment by Corgam** [comment] 2020-12-03 10:15
> So if that is a complete list of all mods, then that means this error is occuring with multiple mods.

Did you try running it without any other mods?

**Comment by DrUltraLux** [comment] 2020-12-03 10:59
> > So if that is a complete list of all mods, then that means this error is occuring with multiple mods.
> 
> Did you try running it without any other mods?

I tried running it on it's own and it works perfectly fine, so it is definitely a mod conflict issue. 

As I said, I also tried disabling all of the mods our two lists had in common, and still got the same error.

**Comment by MachinegunMarty** [comment] 2020-12-03 11:45
Forge 35.1.7
CagedMobs 1.2.5

Had some spare time today.

I found the problem !

I made a new world with just CagedMobs 1.2.5 (client and server) and can log in just fine.
Then i started adding in mods 1 by 1.

As soon as i added Thermal Foundation it started to give the error.
So i tried with all the mods, except Thermal Foundation and i could log in just fine !

So to be sure i tested again and the only mods i used on Server and Client were:
CagedMobs 1.2.5
CoFH_core (Latest)
Thermal Foundation ( Latest)

and the error showed up. 
( to be more precise you can add CoFH_Core without a problem)
So as soon as i add Thermal Foundation the error starts and i can't log in to the world. 
(Thermal Foundation needs CoFH_Core to run, and the rest of the thermal mods need Thermal Foundation to run.)

I looked in my existing world if Thermal adds any arrows, but it doesn't (to narrow it down even more for you)

So it's your mod and Thermal Foundation that are biting each other.

Like i said i added all of the other mods on my list and i can log in just fine.

Hope it helps you out with finding the culprit, at least now you know where to look for it.

**Comment by Corgam** [comment] 2020-12-03 13:34
Amazing! I just tried it and it also crashed, I will try to fix it today or tomorrow. If it's not possible I will remove for now the Thermal support.

**Comment by Corgam** [comment] 2020-12-03 22:16
Ok, it will be fixed in the next version! There is still a problem with rendering of the models, but the functionality works and what is more important, it doesn't crash ;)

**Comment by DrUltraLux** [comment] 2020-12-04 00:06
> Ok, it will be fixed in the next version! There is still a problem with rendering of the models, but the functionality works and what is more important, it doesn't crash ;)

I still had the crash issue even after removing Thermal Foundation, but hoping that your fix might resolve it for whatever other mod is also causing issues.

**Comment by Corgam** [comment] 2020-12-04 08:44
It turned out it was a problem with more then one supported mods, but I hope I fixed all of them. 
I will upload the new version tomorrow

**Comment by DrUltraLux** [comment] 2020-12-04 11:23
> It turned out it was a problem with more then one supported mods, but I hope I fixed all of them.
> I will upload the new version tomorrow

As soon as you do I'll test it with our pack and post the results. 

EDIT: Fixed and working. 👍

**Comment by Corgam** [comment] 2020-12-05 21:48
Ok, I just uploaded 1.2.6 version, I hope it will fix the problem, but there is still a bug with entity model rendering.

**Comment by galveyra** [comment] 2020-12-05 21:51
> 
> 
> > It turned out it was a problem with more then one supported mods, but I hope I fixed all of them.
> > I will upload the new version tomorrow
> 
> As soon as you do I'll test it with our pack and post the results.

Hey, just checking if it's already possible to get the updated mod? 
I'd like to include it on the server that we play on, but it doesn't mix well with the current mods that we're using.
Don't want to start it until I get this mod running as well, since it looks really good and fun to play with!

**Comment by Corgam** [comment] 2020-12-05 22:35
> Hey, just checking if it's already possible to get the updated mod?
> I'd like to include it on the server that we play on, but it doesn't mix well with the current mods that we're using.
> Don't want to start it until I get this mod running as well, since it looks really good and fun to play with!

Please check the 1.2.6 version, the problem should be fixed.

**Comment by Corgam** [comment] 2020-12-08 14:20
Seems like it's not crashing in the newest version, cool.

**Closed as completed by Corgam** 2020-12-08 14:20 UTC
