### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by NevetsBBG** [Corgam/CagedMobs#4] opened 2020-11-05 14:32 UTC
Client Crash after show Recepie in Jei
[crash-2020-11-04_21.57.16-client.txt](https://github.com/Corgam/CagedMobs/files/5494981/crash-2020-11-04_21.57.16-client.txt)

**Comment by Corgam** [comment] 2020-11-05 14:42
Thank you for the issue. Marked as a duplicate of #1

**Closed as completed by Corgam** 2020-11-05 14:42 UTC
